# Generated by Django 4.1.5 on 2023-02-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finds', '0004_alter_finds_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finds',
            name='status',
        ),
        migrations.AddField(
            model_name='finds',
            name='types',
            field=models.CharField(choices=[('LOSTED', 'LOSTED'), ('FOUND', 'FOUND')], default=0, max_length=200),
            preserve_default=False,
        ),
    ]
