# Generated by Django 4.1.6 on 2023-02-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finds', '0005_remove_finds_status_finds_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finds',
            name='types',
            field=models.CharField(choices=[('LOST', 'LOST'), ('FOUND', 'FOUND')], max_length=200),
        ),
    ]
